### ISSUE TITLE
Release for Scala 2.12.0-RC2

### ISSUE THREAD

**Issue by larsrh** [scodec/scodec-scalaz#8]
... if you don't mind :smile:

**Comment by mpilquist** [comment]
@larsrh Sure -- what version are you on now? I should release a 1.3.0 that's built against scodec 1.10.3, Scala 2.{10,11,12} and Scalaz 7.{1,2}. Will that work for you?

**Comment by larsrh** [comment]
Yes, that would work perfectly.

**Comment by mpilquist** [comment]
1.4.0 for Scalaz 7.1.10 and 1.4.0a for 7.2.6 are on their way to Central now.

**Comment by larsrh** [comment]
Thanks!

**Comment by larsrh** [comment]
Same for 2.12.0 final, please :smile:

**Comment by mpilquist** [comment]
@larsrh 1.4.1 and 1.4.1a are on their way to Central now. :)
